### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by wessel145** [Retrospected/app.picnic#11]
First of all, awesome work on reversing the API (been trying this for a while now without success). Are you willing to share your magic? 

The endpoint I'm looking for is to extract nutrition data from a certain article ID.

Thanks in advance!

**Comment by Retrospected** [comment]
hi @wessel145, thanks for your message. What usually works is to configure a proxy server on your mobile device and use a proxy server such as Burp on your laptop. This will intercept all HTTP(s) traffic coming from and to your mobile device. Make sure to import the CA Certificate of your proxy server in your mobile device in order to trust the proxy server.

You can follow the guide below to set it up:
https://support.portswigger.net/customer/portal/articles/1841101-configuring-an-android-device-to-work-with-burp

**Comment by wessel145** [comment]
Thanks for your response. I tried that technique (using mitmproxy) and the app wouldn't make connection. This probably is because of certificate pinning in the app itself. I've tried to engineer my way around it, without any success yet. I might try again

**Comment by Retrospected** [comment]
in that case that would be new, haven't seen any cert pinning the last time i intercepted the traffic (probably about a year ago)

you could try and reverse the .apk file to look at the code of the android app to try and figure it out, but that's a bit more difficult. My api calls in this app should still work though.

**Comment by wessel145** [comment]
Thanks, I think I'll succeed with Fridia

https://medium.com/@ved_wayal/hail-frida-the-universal-ssl-pinning-bypass-for-android-e9e1d733d29
